name: Publish to Test.PyPI.org

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish distribution 📦 to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Installing python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Generating version file
        run: python freeze_version.py
      - name: Setup python wheel
        run: pip install wheel
      - name: Building Package
        run: python setup.py bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          password: pypi-AgENdGVzdC5weXBpLm9yZwIkMTBhNTJmNDctM2MzYy00MjA4LThhODEtMjkxODMzN2JlYmU0AAIWWzEsWyJweXRob24tbXMtY29yZSJdXQACLFsyLFsiN2VkYjhjNmYtNmFmNC00ZDJlLThkMjQtYjY5NjA0YWVkZGVjIl1dAAAGIDDY7BAgBsaR0c-SQC14K-J_yWUT-AA6vQCx5pe4OfJq
          repository_url: https://test.pypi.org/legacy/