name: Publish to PyPI.org
on:
  release:
    types: [ published ]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Git installation
        run: pip install gitpython
      - name: Generating version file
        run: python freeze_version.py
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Setup python wheel
        run: pip install wheel
      - name: Building Package
        run: python setup.py bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          password: pypi-AgENdGVzdC5weXBpLm9yZwIkMTBhNTJmNDctM2MzYy00MjA4LThhODEtMjkxODMzN2JlYmU0AAIWWzEsWyJweXRob24tbXMtY29yZSJdXQACLFsyLFsiN2VkYjhjNmYtNmFmNC00ZDJlLThkMjQtYjY5NjA0YWVkZGVjIl1dAAAGIDDY7BAgBsaR0c-SQC14K-J_yWUT-AA6vQCx5pe4OfJq
          repository_url: https://test.pypi.org/legacy/
#      - run: python3 -m pip install --upgrade build && python3 -m build
#      - name: Publish package
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}