name: Publish to Test.PyPI.org

env:
  TEST_PYPI_API_TOKEN: pypi-AgENdGVzdC5weXBpLm9yZwIkOWFkYzA1NWMtYmE3NC00N2UwLTlmYTctYjhjN2JmMTk5ZmY4AAIWWzEsWyJweXRob24tbXMtY29yZSJdXQACLFsyLFsiN2VkYjhjNmYtNmFmNC00ZDJlLThkMjQtYjY5NjA0YWVkZGVjIl1dAAAGII9pKBoNEcb37cEqKCRcRrWxu2nCVoL8w5WMbLpCnk1u


on:
  push:
    branches:
      - develop
      -
jobs:
  publish:
    name: Publish distribution 📦 to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Installing python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Generating version file
        run: python freeze_version.py
      - name: Setup python wheel
        run: python setup.py bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: $TEST_PYPI_API_TOKEN
          repository_url: https://test.pypi.org/legacy/